version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        databases:
          default:
            connector: postgres
            host: postgres
            user: "${POSTGRES_USER}"
            password: "${POSTGRES_PASSWORD}"
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
